apiVersion: v1
kind: Service
metadata:
  name: umi-backend
spec:
  selector:
    app: umi-backend
  ports:
    - port: 8080
  type: NodePort
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: umi-backend
  labels:
    app: umi-backend
spec:
  replicas: 1
  template:
    metadata:
      name: umi-backend
      labels:
        app: umi-backend
    spec:
      containers:
        - name: umi-backend
          image: zhqn.com:5000/umi-backend:1.0.0
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/godemo/config.json
              name: configFile
            - mountPath: /etc/go03/
              name: esCrtFile
      restartPolicy: Always
      volumes:
        - name: configFile
          configMap:
            name: umi-backend-config
  selector:
    matchLabels:
      app: umi-backend
