apiVersion: v1
kind: Service
metadata:
  name: umi-web
spec:
  selector:
    app: umi-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: umi-web
  labels:
    app: umi-web
spec:
  replicas: 1
  template:
    metadata:
      name: umi-web
      labels:
        app: umi-web
    spec:
      containers:
        - name: umi-web
          image: zhqn.com:5000/umi-web:1.0.0
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: ngnix-conf
      restartPolicy: Always
      volumes:
        - name: ngnix-conf
          configMap:
            name: ngnix-conf
  selector:
    matchLabels:
      app: umi-web
---
apiVersion: v1
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        #access_log  /var/log/nginx/host.access.log  main;

        location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
                try_files $uri $uri/ /index.html;
        }
        location /api/ {
                proxy_pass      http://umi-backend:8282/;
                proxy_set_header X-Real-IP $remote_addr;
        }
    }
kind: ConfigMap
metadata:
  name: ngnix-conf

